# Generated by Django 3.2 on 2021-04-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('date', models.CharField(default=False, max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('image', models.FileField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Loging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=45)),
                ('password', models.CharField(default=False, max_length=45)),
            ],
        ),
    ]
