from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index1', views.index1, name='index1'),
    path('about', views.about, name='about'),
    path('bakery', views.bakery, name='bakery'),
    path('beverages', views.beverages, name='beverages'),
    path('cleaning', views.cleaning, name='cleaning'),
    path('confictionery', views.confictionery, name='confictionery'),
    path('construction', views.construction, name='construction'),
    path('contact', views.contact, name='contact'),
    path('fabric_care', views.fabric_care, name='fabric_care'),
    path('foodingredients', views.foodingredients, name='foodingredients'),
    path('machinery_equipment', views.machinery_equipment, name='machinery_equipment'),
    path('meat', views.meat, name='meat'),
    path('paint_coating', views.paint_coating, name='paint_coating'),
    path('paint', views.paint, name='paint'),
    path('polymer', views.polymer, name='polymer'),
    path('pre_mixes', views.pre_mixes, name='pre_mixes'),
    path('chemicals', views.chemicals, name='chemicals'),
    path('water', views.water, name='water'),
    path('events', views.events, name='events'),
    path('services', views.services, name='services'),
    path('login', views.login, name='login'),
    path('log', views.log, name='log'),
    path('eventform', views.eventform, name='eventform'),
    path('viewevent', views.viewevent, name='viewevent'),
    path('index2', views.index2, name='index2'),
    path('blog', views.blog, name='blog'),
    path('imageupload', views.imageupload, name='imageupload'),
    path('deleteevent', views.deleteevent, name='deleteevent'),
    path('viewgallery', views.viewgallery, name='viewgallery'),
    path('logout_view', views.logout_view, name='logout_view'),
]